version: 2

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    reviewers:
      - 'stackrox/maple'
      - 'RTann'

  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    reviewers:
      - 'stackrox/maple'
      - 'RTann'
  - package-ecosystem: 'gomod'
    directory: '/_integration-tests'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    reviewers:
      - 'stackrox/maple'
      - 'RTann'
  - package-ecosystem: 'gomod'
    directory: '/tools'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    reviewers:
      - 'stackrox/maple'
      - 'RTann'

